[project]
name = "tm1mcp"
version = "0.1.0"
description = "TM1 MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "tm1py>=2.1.0",
    "mcp[cli]>=1.8.0",
    "mdxpy>=1.3.2",
]
